### ISSUE TITLE
Error when exporting to gcode

### ISSUE THREAD

**Issue by a-brico** [Heinz-Loepmeier/nozzleboss#5]
I get the following error when trying to export to g-code when following your tutorial on youtube.

"Python: Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Blender/4.1/scripts/addons/nozzleboss-main/nozzleboss.py", line 467, in execute
    return export_gcode(context)   
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Library/Application Support/Blender/4.1/scripts/addons/nozzleboss-main/nozzleboss.py", line 324, in export_gcode
    verts = read_verts(obj.data)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Library/Application Support/Blender/4.1/scripts/addons/nozzleboss-main/utils.py", line 6, in read_verts
    mverts_co = np.zeros((len(mesh.vertices) * 3), dtype=np.float)
                                                         ^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?"

I have tried changing the np.float to both float and np.float64 in utils.py with the same error on line 6 as a result. I'm not sure if the error is due to my setup. Would be very thankful for some guidance on how to solve the problem.

**Comment by Heinz-Loepmeier** [comment]
Fixed (some deprecated numpy syntax for Blender 4.1).
Can you test again?

**Comment by a-brico** [comment]
Thanks a lot for your help. I previously tried the changes that you describe and got the same error messages showing the new line with the updated dtype=float. So I was sure it had been saved. I realised later I just needed to restart blender as well and this made the error message go away and everything work. However np.int also needs to be changed to int in the same file to make it work. This still needs updating in the current version on github.

Something I have noticed is that the gcode exported overlooks the last piece of the extruded path for every layer. See attached screenshot. I don't know if there is an easy fix for this?

<img width="1226" alt="Screenshot 2024-04-24 at 22 45 38" src="https://github.com/Heinz-Loepmeier/nozzleboss/assets/167528294/da6cbc25-886b-4825-9ed4-9d5d9e6ace7a">

Also after doing a lattice deformation on part of the model the parts of the extruded lines moving towards the centre have a slightly narrower layer width compared to the parts of the lines moving away from the centre. I don't think this would have any noticeable impact on the print though.

**Comment by Heinz-Loepmeier** [comment]
Fixed the np.int on github. You can search Blender for "reload scripts" to update any changed .py files without a restart.  

To close the shape in the current version, you need to overlap the last and first vertex of your shape or try https://github.com/Heinz-Loepmeier/nozzleboss-dev/ which does that for you. Let me know if it works. 

Different width after deformation should be normal ,because deforming the faces will give you a different segment height/volume. This is good and helps you to get the right extrusion volume for your deformed layer height.

**Comment by a-brico** [comment]
That is amazing! It works now right from the box and the dev version also fixes the gap problem I had perfectly.

For my last point I think I didn't do a very good job in explaining what I meant however. I agree that it is good that the extrusion value changes after deformation depending on the new geometry of the extruded line. The change of line width/flow I noticed however doesn't seem to be related to the new geometry of the line in blender. Two identical sections of the extruded line only differing in the direction of printing, gets different layer width in the gcode. I have made a minimal reproducible example in blender by extruding a star shape and doing a lattice deformation. 
[MRE.blend.zip](https://github.com/Heinz-Loepmeier/nozzleboss/files/15122891/MRE.blend.zip)
The shape exports with a large difference in line width depending on printing direction as seen in the picture. I'm not sure if this effect only appears as a result of this specific deformation method or is more general.
<img width="798" alt="Screenshot 2024-04-26 at 00 13 44" src="https://github.com/Heinz-Loepmeier/nozzleboss/assets/167528294/ac15f770-dfcb-4866-bf1e-05b86b66ed30">

**Comment by Heinz-Loepmeier** [comment]
Ah I see, the example helps alot.
In your star example file the extrusion width varies, because the height edges are different.  

![exw](https://github.com/Heinz-Loepmeier/nozzleboss/assets/17910445/9bd2c685-e658-4215-be6d-60e6e453e39d)
V0 to V1 uses a height of **1.1mm** (and a width of height*1.2), V1 to V2 uses a height of **1.8mm**

V0-V14 is the actual extrusion path, the other half is just used to calc the heights of the segments.  
If you want a more constant extrusion width, you can try to extrude after the deformation.  
Though many operations require faces in blender, so you can also try to extrude by zero, then do your operations and only then translate the zero extrusion to something else.  

Let me know if you run into any problems.

**Comment by a-brico** [comment]
Now I see. This makes sense then. I had assumed the that the extrusion number was based on the average height between the start and end point of each segment or perhaps the area of each segment. This would be the same for all segments in the example why I expected the extrusion to also be the same.

Thanks for the tip of extruding after deformation, that could be a great workaround when working with lines generated directly in blender. But I think it might be less useful on imported g-code especially if one wants to preserve some of the information about varying line widths.

I don't know if it would be possible to add the option of exporting the g-code using a different way of calculating the extrusion value. Either the area of each segment of the extruded line divided by the length of the segment can be used as a "substitute height" to calculate extrusion. Or what would be even better I believe would be to use the ratio of after to before deformation of these "substitute heights" and multiplying this by the original height i.e. original height⋅(new segment area/new segment length)/(old segment area/old segment length). I believe both these option even though not perfect could fix the problem in most cases and the second might be even better when there is more rapid changes in line width etc.

**Comment by Heinz-Loepmeier** [comment]
Current importer can't deal width varying line width. Future version will have an option to import original E and F values to an attribute map.  
Not sure if mixing original with newly deformed geometry would help. Extrusion volume should just be height*width*length (+some extra checks that width doesn't become smaller than nozzle diameter).  
Everything more complicated could be achieved with Blender; mixing two geometries with weighted shapes keys, masking extruded verts ect.

**Comment by a-brico** [comment]
As I understood it the importer can still import G code with varying line width but will represent this as differing height of the segments, is this correct?

I think my original explanation for why to calculate the extrusion number differently wasn’t clear and as you say thinking of the height*width*length formula makes more sense rather than what I was saying of calculating a substitute height to add in this formula. I have thought a bit more about how to solve the under and over-extrusion problems and I think I’ve come up with an easier way basing extrusion values on area instead.

Trying to be more clear this time I’ve made some figures to explore the problems and potential solutions. Please have a look and let me know if you see any problems with it or misunderstandings from my side and if you think it is possible to implement in blender or not.

[Overly detailed explanation.pdf](https://github.com/Heinz-Loepmeier/nozzleboss/files/15154797/Overly.detailed.explanation.pdf)

**Comment by Heinz-Loepmeier** [comment]
Current importer will set a fixed layer height based on the distance to the previous layer, so no varying extrusion width.  
Overly detailed explanation.pdf is not wrong, calculating by area is more accurate, but you can subdivide the path on import to minimize the different between both polygon height edges. 
Also overly trapezoid shaped polygons can cause overextrusion, but more often than not, I want this heavy deformation be reflected in the extrusion rate. In the past I used a flow weightmap based on face area to compensate for that https://youtu.be/aoM8-Xdh9w8?t=98 (but there are other factors at work here, by finding bigger polygons here you also indentify areas of overlapping paths...)  
I'll keep a more accurate volume calc in mind in the future, but for I know I prefer a simplification. Feel free to provide me with any practical examples of prints where better calc would be helpful.

**Comment by Heinz-Loepmeier** [comment]
by the way you might be interested in a small Open CAM FFF discord, just to share some quick ideas.
https://discord.gg/9NnMEdhe

**Comment by a-brico** [comment]
Thanks for the invite! I've joined the group.

I was struggling a bit with the flow weightmap based on area and I didn't manage to correct for the extrusion differences I was seeing, I guess the over-extrusion isn't related to area in this case. For example the "deform after extrude" mesh in the blender file. [test_shapes.blend.zip](https://github.com/Heinz-Loepmeier/nozzleboss/files/15267604/test_shapes.blend.zip) Of course deforming before extrusion solves the problem. Other than that I really like these weightmap features, but have barely scratched the surface so far.

I tried changing your code a bit to try out extrusion based on area and also based on z-height difference. I get some good results on some deformed models with the same segment shape always giving the same extrusion value regardless of the direction of print. I also decided to set the nozzlepath as the midpoint of the height edge to achieve better consistency. I'll try uploading it as a fork.

**Comment by Myrkskog** [comment]
> by the way you might be interested in a small Open CAM FFF discord, just to share some quick ideas. https://discord.gg/9NnMEdhe

Very exclusive channel? Or might you have another invite laying around?

Also, @Heinz-Loepmeier since you obviously have a hang of python. Have you tried pyicesl?
